# Generated by Django 3.2.7 on 2022-03-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numbers', models.BigIntegerField(default=0, verbose_name='Номер карты')),
                ('Relase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска карты')),
                ('End_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания активности карты')),
                ('Use_date', models.DateTimeField(blank=True, verbose_name='Дата использования')),
                ('Summ', models.IntegerField(default=0, verbose_name='Сумма')),
                ('Stutus', models.CharField(choices=[('не активирована', 'не активирована'), ('активирована', 'активирована'), ('просрочена', 'просрочена')], default='не активирована', max_length=100, verbose_name='Статус карты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='TypeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=250, verbose_name='Тип карты')),
            ],
            options={
                'verbose_name': 'Тип карты',
                'verbose_name_plural': 'Типы карт',
            },
        ),
        migrations.CreateModel(
            name='SeriesCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.CharField(max_length=250, verbose_name='Серия карты')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcards.typecard', verbose_name='Тип карты')),
            ],
            options={
                'verbose_name': 'Серия карты',
                'verbose_name_plural': 'Серии карт',
            },
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Use_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('Summ', models.IntegerField(default=0, verbose_name='Сумма покупки')),
                ('Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcards.carddata', verbose_name='Номер серии')),
            ],
            options={
                'verbose_name': 'История карты',
                'verbose_name_plural': 'Истории карты',
            },
        ),
        migrations.AddField(
            model_name='carddata',
            name='Series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankcards.seriescard', verbose_name='Серия карты'),
        ),
    ]
