# Generated by Django 3.2.7 on 2022-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcards', '0002_rename_series_historycard_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecard',
            name='Type',
            field=models.CharField(max_length=250, unique=True, verbose_name='Тип карты'),
        ),
    ]
