# Generated by Django 3.2.7 on 2022-03-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcards', '0004_alter_carddata_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddata',
            old_name='Stutus',
            new_name='Status',
        ),
    ]
