# Generated by Django 3.2.7 on 2022-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcards', '0005_rename_stutus_carddata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard')], max_length=250, verbose_name='Серия карты')),
                ('kolvo', models.IntegerField(default=0, verbose_name='Колчество карт')),
            ],
        ),
        migrations.AlterField(
            model_name='carddata',
            name='End_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания активности карты'),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='Use_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата использования'),
        ),
    ]
